test: add e2e tests for navigating to multiple views in the same execution stack
SchweizerischeBundesbahnen/scion-workbench pull request #349
Opened 2022-09-09 11:53 UTC by mofogasy

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [guidelines](https://github.com/SchweizerischeBundesbahnen/scion-workbench/blob/master/CONTRIBUTING.md)
- [x] Tests for the changes have been added
- [ ] Docs have been added or updated

## PR Type
What kind of change does this PR introduce?

- [ ] Fix
- [ ] Feature
- [ ] Documentation
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Performance (changes that improve performance)
- [x] Test (adding missing tests, refactoring tests; no production code change)
- [ ] Chore (other changes like formatting, updating the license, removal of deprecations, etc)
- [ ] Deps (changes related to updating dependencies)
- [ ] CI (changes to our CI configuration files and scripts)
- [ ] Revert (revert of a previous commit)
- [ ] Release (publish a new release)
- [ ] Other... Please describe:

## Issue

Issue Number: #254 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-09-10 05:01 UTC, danielwiehl requested changes

2022-09-13 05:44 UTC, mofogasy commented on apps/workbench-client-testing-app/src/app/activator/activator.module.ts
> +        pinToStartPage: true,
For now, I think we can go with the first approach. We should keep in mind the second approach though, as soon as more test pages are added.

2022-09-13 05:45 UTC, mofogasy commented on apps/workbench-client-testing-app/src/app/bulk-navigation-page/bulk-navigation-page.component.scss
> +  display: grid;
Done

2022-09-13 05:53 UTC, mofogasy commented on projects/scion/e2e-testing/src/workbench-client/bulk-navigation.e2e-spec.ts
> +    const bulkNavigationPagePO = await microfrontendNavigator.openInNewTab(BulkNavigationPagePO, 'app1');
Done

2022-09-13 05:55 UTC, mofogasy commented on projects/scion/e2e-testing/src/workbench-client/page-object/bulk-navigation-page.po.ts
> +    await this._appPO.page.locator(`wb-view-tab.e2e-test-view`).nth(9).waitFor({state: 'attached'});
Done

2022-09-13 05:57 UTC, mofogasy commented on projects/scion/e2e-testing/src/workbench-client/page-object/bulk-navigation-page.po.ts
> +
Done

2022-09-13 06:00 UTC, mofogasy commented on projects/scion/e2e-testing/src/workbench/page-object/bulk-navigation-page.po.ts
> +  public async clickNavigateNoAwait(): Promise<void> {
Done

2022-09-13 14:51 UTC, mofogasy commented on projects/scion/e2e-testing/src/workbench/bulk-navigation.e2e-spec.ts
> +    await expect(await appPO.getViewTabCount()).toEqual(11);
Done

2022-09-13 14:51 UTC, mofogasy commented on apps/workbench-client-testing-app/src/app/bulk-navigation-page/bulk-navigation-page.component.ts
> +const VIEWS_COUNT = 10;
Done

2022-09-13 14:51 UTC, mofogasy commented on apps/workbench-client-testing-app/src/app/bulk-navigation-page/bulk-navigation-page.component.ts
> +  private navigateToViewPage(): Promise<boolean> {
Done

2022-09-16 06:55 UTC, mofogasy commented on projects/scion/e2e-testing/src/workbench-client/page-object/bulk-navigation-page.po.ts
> +    await assertElementVisible(this._locator);
No, we can it remove from all tests

2022-09-16 17:01 UTC, danielwiehl requested changes
Almost perfect. Please see me review commit.

2022-09-19 13:34 UTC, danielwiehl approved these changes

2022-09-19 13:34 UTC, merged